### PR TITLE
Fix useless use of cat

### PR DESCRIPTION
**Pull request by rpdelaney**
I couldn't stand looking at it. :D

### CODE REVIEW

**Comment by ferlatte** [comment]
We actually left the cat in there on purpose; the ./program < input > output syntax regularly confuses and astounds people who understand the cat input | ./program > output syntax.

**Comment by ferlatte** [comment]
I am not a huge fan of it either and in this case, since we're not evaluating on Unix pipeline skills, I think we probably should leave the cat.

**Comment by chrisgilmerproj** [comment]
You could leave both in and do this:

```
`cat sample.csv | ./normalizer > output.csv`

Similarly, this should work:

`./normalizer < sample.csv > output.csv`
```

**Comment by ferlatte** [comment]
@chrisgilmerproj suggestion works for me.

**Comment by rpdelaney** [comment]
Context: while this PR admittedly creates the appearance of rank pedantry, my thought was to represent ourselves from the very beginning according to our values "Seek the highest standard", "Make the best move, not the safest one", and "Help people follow us". With that said the point is that these two formulations are not syntactically equivalent: one is actually just worse than the other.

`cat file | foo` is more intuitive to lots of folks, and it will not perform perceptibly worse on modern hardware running on files this small. But it's nevertheless just _wrong_ to do it that way -- that syntax will exhibit inferior performance with big files or in scripts that are being executed repeatedly / rapidly / recursively, because it spawns an extra subprocess and copies the file one more time in memory than should be necessary.

From a technical point of view, `foo < file` is just a strict upgrade. 

Putting all that together, I'd actually be more inclined to withdraw this PR than go with the compromise of having both. But enough breath has been spent on this, so whatever you folks think is best is fine with me.

**Comment by ferlatte** [comment]
You know what? Let's try it and see; maybe I'm assuming something about folks ability to understand the syntax. I'm gonna merge it.

**Pull request merged**
