### PR TITLE
Expand example of how stdin/stdout will be tested by Truss

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
In two separate technical interviews I observed that the use of stdin/stdout wasn't clear to the candidate.  I thought perhaps handing them an example of how we would use the code would be helpful here.

I'm open to suggestions on this because I'm not convinced I've made it any clearer to people that don't know stdin/stdout with this change.

### CODE REVIEW

**Review by macrael — COMMENTED** [review]
Looks good to me. @ferlatte what do you think about this clarification?

**Review by ferlatte — COMMENTED** [review]
i'd be even more explicit and redirect the output also.

./yourprogram < sample.csv > output.csv

cat is fine

**Comment by chrisgilmerproj** [comment]
I did this:

```
cat sample.csv | ./normalizer > output.csv
```

**Comment by ferlatte** [comment]
Thanks!

**Pull request merged**
